site :opscode

cookbook 'apt'
cookbook 'git'
cookbook 'build-essential'
cookbook 'libqt', path: 'cookbooks/libqt'
cookbook 'ruby_build'
cookbook 'rbenv', git: 'git://github.com/fnichol/chef-rbenv.git', ref: 'v0.7.2'
cookbook 'mysql'
